# action.yml
name: 'Name: Merge Local settings yml with the global one'
description: 'Description: Merge Local settings yml with the global one'
inputs:
  globalSettingYml:
    description: 'the global settings yml for repo'
    required: true
  localSettingYml:
    description: 'the local settings yml for repo'
    required: true
outputs:
  mergedSettingsYml:
    description: 'the merged settings yml for repo'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.globalSettingsYml }}
    - ${{ inputs.localSettingsYml }}