# action.yml
name: 'Name: Merge Local settings yml with the global one'
description: 'Description: Merge Local settings yml with the global one'
inputs:
  localSettingsYml:
    description: 'the local settings yml for repo'
    required: true
  token:
    description: 'token for repo'
    required: true
  user:
    description: 'user for repo'
    required: true
outputs:
  mergedSettingsYml:
    description: 'the merged settings yml for repo'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.localSettingsYml }}
    - ${{ inputs.token }}
    - ${{ inputs.user }}
