#!/usr/bin/env php
<?php

if(file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

$globalSettingsYml = getenv('globalSettingsYml') ?getenv('globalSettingsYml') : $argv[1];
$localSettingsYml = getenv('localSettingsYml') ?getenv('localSettingsYml'): $argv[2];

use Symfony\Component\Yaml\Yaml;

$globalSettingsYml = Yaml::parse(file_get_contents($globalSettingsYml));
$localSettingsYml = Yaml::parse(file_get_contents($localSettingsYml));
$mergedSettingsYml = $globalSettingsYml;
echo 'local' . $localSettingsYml;
echo '   global' . $globalSettingsYml;
echo '    merged' . $mergedSettingsYml;

foreach($globalSettingsYml as $key => $value)
{
    if(array_key_exists($key, $localSettingsYml))
    {
        $mergedSettingsYml[$key] = $localSettingsYml[$key];
    }
}
echo '::set-output name=mergedSettingsYml::' . json_encode($mergedSettingsYml);
