#!/usr/bin/env php
<?php

if(file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

$localSettingsYml = getenv('localSettingsYml') ?getenv('localSettingsYml'): $argv[1];
$token = getenv('GHA_TOKEN')?getenv('GHA_TOKEN'): $argv[2];
$user = getenv('GHA_USER')?getenv('GHA_USER'): $argv[3];

use Symfony\Component\Yaml\Yaml;

$url = "https://api.github.com/repos/ZooRoyal/GlobalRepoManagerSettings/contents/.github/settings-global.yml";

$ch = curl_init();
curl_setopt_array($ch, [
    CURLOPT_URL => $url,
    CURLOPT_HTTPHEADER => [
        "Accept: application/vnd.github.v3+json",
        "Content-Type: text/plain",
        "Authorization: token " . $token,
        "User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 YaBrowser/16.3.0.7146 Yowser/2.5 Safari/537.36"
    ],
    CURLOPT_RETURNTRANSFER => true,
]);
$response = curl_exec($ch);
curl_close($ch);
$file_content = json_decode($response, true);

$globalSettingsYml = Yaml::parse(base64_decode($file_content['content']));
$localSettingsYml = Yaml::parse(file_get_contents($localSettingsYml));
$mergedSettingsYml = $globalSettingsYml;

foreach($globalSettingsYml as $key => $value)
{
    if (array_key_exists($key, $localSettingsYml)) {
        $mergedSettingsYml[$key] = $localSettingsYml[$key];
    } else {
        $mergedSettingsYml[$key] = $value;
    }
}
echo ' from here output    ';
echo '::set-output name=mergedSettingsYml::' . json_encode($mergedSettingsYml);
